export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","title":"RUI","i":"home"},["/index.html","/README.md"]],
  ["v-0fa91989","/begin.html",{"y":"a","title":"目录","i":"creative"},["/begin","/begin.md"]],
  ["v-2e3eac9e","/slides.html",{"y":"s","title":"幻灯片","i":"slides"},["/slides","/slides.md"]],
  ["v-510a7ac4","/Learn/",{"y":"h","title":"学习","i":"home"},["/Learn/index.html","/Learn/README.md"]],
  ["v-48659f94","/Learn/begin.html",{"y":"a","title":"目录","i":"creative"},["/Learn/begin","/Learn/begin.md"]],
  ["v-1323413a","/Life/",{"y":"h","title":"生活","i":"home"},["/Life/index.html","/Life/README.md"]],
  ["v-5fad6aec","/Life/begin.html",{"y":"a","title":"开始","i":"creative"},["/Life/begin","/Life/begin.md"]],
  ["v-1094e2aa","/Learn/Docker/",{"y":"a","title":"Docker","i":"creative"},["/Learn/Docker/index.html","/Learn/Docker/README.md"]],
  ["v-bc8fdcc2","/Learn/Linux/",{"y":"a","title":"Linux","i":"creative"},["/Learn/Linux/index.html","/Learn/Linux/README.md"]],
  ["v-5af4c7e0","/Learn/RM/",{"y":"a","title":"RM","i":"layout"},["/Learn/RM/index.html","/Learn/RM/README.md"]],
  ["v-81881202","/Life/shop/",{"y":"a","title":"购物","i":"creative"},["/Life/shop/index.html","/Life/shop/README.md"]],
  ["v-205370b2","/Learn/Docker/bar/",{"y":"a","title":"Bar feature","i":"creative"},["/Learn/Docker/bar/index.html","/Learn/Docker/bar/README.md"]],
  ["v-0f9bce45","/Learn/Docker/bar/baz.html",{"y":"a","title":"Baz","i":"info"},["/Learn/Docker/bar/baz","/Learn/Docker/bar/baz.md"]],
  ["v-2539c8d5","/Learn/Linux/Alpine/",{"y":"a","title":"Alpine","i":"layout"},["/Learn/Linux/Alpine/index.html","/Learn/Linux/Alpine/README.md"]],
  ["v-70e0f6e9","/Learn/Linux/Alpine/encrypt.html",{"y":"a","title":"测试文章","i":"lock"},["/Learn/Linux/Alpine/encrypt","/Learn/Linux/Alpine/encrypt.md"]],
  ["v-24d87382","/Learn/Linux/openwrt/",{"y":"a","title":"openwrt","i":"layout"},["/Learn/Linux/openwrt/index.html","/Learn/Linux/openwrt/README.md"]],
  ["v-1643e2a0","/Learn/Linux/openwrt/disable.html",{"y":"a","title":"测试文章","i":"config"},["/Learn/Linux/openwrt/disable","/Learn/Linux/openwrt/disable.md"]],
  ["v-c14f472a","/Learn/RM/BUG/",{"y":"a","title":"遇到的问题","i":"layout"},["/Learn/RM/BUG/index.html","/Learn/RM/BUG/README.md"]],
  ["v-271916d3","/Learn/RM/BUG/footer.html",{"y":"a","title":"Footer","i":"footer"},["/Learn/RM/BUG/footer","/Learn/RM/BUG/footer.md"]],
  ["v-59f2737c","/Learn/RM/BUG/test.html",{"y":"a","title":"密码加密的文章","i":"lock"},["/Learn/RM/BUG/test","/Learn/RM/BUG/test.md"]],
  ["v-56c2231d","/Learn/RM/CONFIG/",{"y":"a","title":"基础配置","i":"config"},["/Learn/RM/CONFIG/index.html","/Learn/RM/CONFIG/README.md"]],
  ["v-0c3e2d2d","/Learn/RM/CONFIG/page.html",{"y":"a","title":"页面配置","i":"page"},["/Learn/RM/CONFIG/page","/Learn/RM/CONFIG/page.md"]],
  ["v-8b346de8","/Learn/RM/CONFIG/ray.html",{"y":"a","title":"Ray","i":"config"},["/Learn/RM/CONFIG/ray","/Learn/RM/CONFIG/ray.md"]],
  ["v-3706649a","/404.html",{"y":"p","title":""},["/404"]],
]
