on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - DOC

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          submodules: true
          
      - name: 切换到SRC分支
        run: git checkout SRC
      
      - name: 克隆文档
        run: git clone https://github.com/bestruirui/RUI_KNOWLEDGE.git
        
        
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          
      - name: 移动文档
        run: mv RUI_KNOWLEDGE/* src/
      
      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run build
          > src/.vuepress/dist/.nojekyll
          
          
      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          branch: PAGE
          folder: src/.vuepress/dist
