on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - DOC

jobs:
  deploy-gh-pages:
    name: 部署页面
    runs-on: ubuntu-latest
    steps:
      - name: 设置时区
      - uses: szenius/set-timezone@v1.1
        with:
           timezoneLinux: "Asia/Shanghai"
           
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          submodules: true
                
      - name: 拉取MOD
        run: git clone https://github.com/bestruirui/RUI_DOCS_NODE_MOD.git

      - name: 移动MOD
        run: mv RUI_DOCS_NODE_MOD/* ..
      
      - name: 删除文件
        run: rm -rf RUI_DOCS_NODE_MOD
        
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: 构建页面
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run build
          > src/.vuepress/dist/.nojekyll
  
      - name: 获取时间
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d-%H:%M')"
          
      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          repository-name: bestruirui/RUI_DOCS_PAGE
          token: ${{secrets.RUI_TOKEN}}
          branch: main
          commit-message: ${{ steps.date.outputs.today }}
          folder: src/.vuepress/dist
